apps/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views.sign_in import SignInView
from users.views.sign_up import SignUpView

urlpatterns = [
    path('sign-in/', SignInView.as_view(), name='sign-in'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),

    path('logout/', LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('main/', include(('main.urls', 'main'), namespace='main')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

apps/users/views/sign_in.py
from django.contrib.auth.views import LoginView


class SignInView(LoginView):
    template_name = 'signin.html'

apps/users/views/sign_up.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.permissions import AllowAny

from users.form.user_creation_form import CustomUserCreationForm


class SignUpView(View):
    permission_classes = [AllowAny]
    template_name = 'signup.html'

    def get(self, request):
        context = {
            'form': CustomUserCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            user.is_staff = True
            user.save()
            login(request, user)
            return redirect('/main/home')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)

apps/users/templates/signin.html
{% extends 'rest_framework/login_base.html' %}


{% block branding %}
<div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 5px">
    <h3 style="margin: 0">Login</h3>
    <a href="{% url 'users:sign-up' %}">
        <button type="submit" class="btn my-2 my-sm-0">Sign up</button>
    </a>
</div>
{% endblock %}

apps/users/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Registration</h1>

<form action="{% url 'users:sign-up' %}" method="POST">
    {{ form }}
    {% csrf_token %}
    <button class="btn btn-success m-2">Submit</button>
</form>

{% endblock %}